<!DOCTYPE html>
<html>
<head>
    <title>New Support Ticket</title>
</head>
<body style="font-family: Arial, sans-serif; background-color: #f4f7f5; padding: 20px;">
    <div style="max-w-md mx-auto bg-white p-8 rounded-lg shadow-md border-top: 4px solid #10b981;">
        <h2 style="color: #064e3b;">New Agri-Trek Support Query</h2>
        <p style="color: #374151; font-weight: bold;">A new message was submitted via the contact form.</p>
        
        <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <tr>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; font-weight: bold; color: #4b5563; width: 30%;">Name:</td>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; color: #111827;">{{ $contactName }}</td>
            </tr>
            <tr>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; font-weight: bold; color: #4b5563;">Email:</td>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; color: #111827;">{{ $contactEmail }}</td>
            </tr>
            <tr>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; font-weight: bold; color: #4b5563; vertical-align: top;">Message:</td>
                <td style="padding: 10px; border-bottom: 1px solid #e5e7eb; color: #111827; background-color: #f9fafb; border-radius: 4px;">{{ $contactMessage }}</td>
            </tr>
        </table>

        <p style="color: #6b7280; font-size: 12px; margin-top: 30px; text-align: center;">This email was automatically generated by the Agri-Trek Platform.</p>
    </div>
</body>
</html>
